dist: bionic

env:
  global:
    secure: "XBCnCpNZ9WfkvDLkwMeW/D/TphPpqDJQdSsC9UOK9HFR3rgBmCof36DlirrZeefF6YKTr3Exkbl/7jDUK7hAGoa1c5NbXqYFp4ne3pSo77G3jHbC0zEP5k2F15NKSo8P9x0QsKzi7Mg1liratz7u65jRqURaZG4kFMw4f0NfVGU="
addons:
  apt:
    sources:
      - sourceline: 'ppa:avsm/ppa'
    packages:
      - opam
      - ocaml-nox
  homebrew:
    packages:
      - opam

matrix:
  include:
  - env: CHECKED=python
    language: python
  - env: CHECKED=js
  - env: USE_TK=1
    addons:
      apt:
        packages:
          - tk-dev
  - env: CHECKED=native
    addons:
      apt:
        packages:
          - gnuplot-nox
          - poppler-utils
          - graphviz
          - texlive-latex-recommended
          - texlive-fonts-recommended
          - texlive-pictures
          - tex4ht
  - os: osx
    env: CHECKED=MacOS
  - env: CHECKED=windows
    addons:
      apt:
        packages:
          - gcc-mingw-w64-x86-64

install:
  - sh -c "if [ '$CHECKED' = windows ] || [ '$CHECKED' = python ] ; then opam init -a --compiler=4.07.0 ; else opam init -a ; fi"
  - sh -c "if [ '$CHECKED' = windows ] ; then opam remote add cross-windows git://github.com/ocaml-cross/opam-cross-windows ; fi"
  - eval $(opam env) && opam install -y dune num yojson lwt fmt logs re decompress
  - sh -c "if [ '$CHECKED' = native ] ; then opam install -y odoc ; fi"
  - sh -c "if [ '$USE_TK' = 1 ] ; then opam install -y labltk ; fi"
  - sh -c "if [ '$TRAVIS_OS_NAME' = osx ] || [ '$CHECKED' = js ] || [ '$CHECKED' = windows ] ; then opam install -y lwt_react tyxml-ppx js_of_ocaml-lwt js_of_ocaml-tyxml atdgen ; fi"
  - sh -c "if [ '$CHECKED' = python ] ; then opam install -y atdgen cohttp-lwt-unix ; fi"
  - sh -c "if [ '$CHECKED' = python ] ; then pip install -v . nose ; fi"
  - sh -c "if [ '$CHECKED' = windows ] ; then opam install -y ocaml-windows64 num-windows atdgen-runtime-windows.2.0.0 lwt-windows fmt-windows logs-windows re-windows decompress-windows ; fi"

script:
  - make all
  - sh -c "if [ '$CHECKED' = native ] ; then make doc_html ; fi"
  - sh -c "if [ '$CHECKED' = native ] ; then make -j2 check ; fi"
  - sh -c "if [ '$CHECKED' = python ] ; then dune build && cd python && nosetests -v ; fi"
  - sh -c "if [ '$CHECKED' = js ] ; then make Kappapp.tar.gz site/index.html ; fi"
  - sh -c "if [ '$TRAVIS_OS_NAME' = osx ] ; then make Kappapp.app ; fi"
  - sh -c "if [ '$CHECKED' = windows ] ; then make KappaBin.zip ; fi"

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ( umask 077 && openssl aes-256-cbc -K $encrypted_942f740de87b_key -iv $encrypted_942f740de87b_iv -in dev/travis-deploy.enc -out dev/travis-deploy -d ) ; fi'

deploy:
  provider: script
  script: dev/update-web.sh "$CHECKED"
  skip_cleanup: true
  on:
    branch: master
